name: Deploy to Surge

on:
  push:
    branches:
      - main  # o la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: configura nodejs  
      uses: actions/setup-node@v3
      with:
        node-version: '22' 


    - name: Install dependencies
      run: npm install --global surge
     

    - name: Deploy to Surge
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      run: surge ./ --domain https://ViannyParcial1.surge.sh.